name: mobile_flutter
description: "Digital building logs for Moscow LDT 03"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_map:
    version:  ^8.2.2
  shared_preferences:
    version: ^2.5.3
  http:
    version: ^1.5.0
  flutter_tesseract_ocr: ^0.4.30
  flutter_native_splash: ^2.4.6
  cupertino_icons: ^1.0.8
  camera: ^0.11.2
  logging: ^1.3.0
  iconify_flutter: ^0.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/images/logo.png
  android: true
  ios: true
  web: false
  android_12:
    color: "#FFFFFF"
    image: assets/images/logo.png
  ios_content_mode: "center"
