tables:
- name: product
  schema: product
  fields:
  - name: title
    type: text
  - name: guid
    type: uuid
    isPrimary: true
    default: gen_random_uuid()
  - name: updated_at
    type: timestamp
    default: LOCALTIMESTAMP
  - name: created_at
    type: timestamp
    default: LOCALTIMESTAMP
  - name: count
    type: integer
