tables:
- name: project
  schema: project
  fields:
  - name: status
    type: integer
  - name: polygon
    type: jsonb
  - name: start_date
    type: date
    nullable: true
    default: null
  - name: end_date
    type: date
    nullable: true
    default: null
  - name: uuid
    type: uuid
    isPrimary: true
    default: "gen_random_uuid()"
  - name: foreman
    type: uuid
    nullable: true
    default: null
  - name: created_at
    type: timestamp
    nullable: false
    default: "LOCALTIMESTAMP"
  - name: address
    type: text
  - name: created_by
    type: uuid
    nullable: true
- name: iko_relationship
  schema: project
  fields:
  - name: project
    type: uuid
  - name: user_uuid
    type: uuid
    nullable: true
    default: null
  - name: uuid
    type: uuid
    isPrimary: true
    default: "gen_random_uuid()"
