tables:
- name: project
  schema: project
  fields:
  - name: status
    type: integer
  - name: polygon
    type: jsonb
  - name: uuid
    type: uuid
    isPrimary: true
    default: "gen_random_uuid()"
  - name: foreman
    type: uuid
    nullable: true
    default: null
  - name: address
    type: text
  - name: ssk
    type: uuid
    nullable: true
    default: null
  - name: is_active
    type: boolean
    nullable: false
    default: false  
- name: iko_relationship
  schema: project
  fields:
  - name: project
    type: uuid
  - name: user_uuid
    type: uuid
    nullable: true
    default: null
  - name: uuid
    type: uuid
    isPrimary: true
    default: "gen_random_uuid()"
