tables:
- name: project
  schema: project
  fields:
  - name: status
    type: integer
  - name: polygon
    type: jsonb
    nullable: true
  - name: uuid
    type: uuid
    isPrimary: true
  - name: foreman
    type: uuid
    nullable: true
  - name: address
    type: text
    nullable: true
  - name: ssk
    type: uuid
    nullable: true
- name: iko_relationship
  schema: project
  fields:
  - name: project
    type: uuid
  - name: user_uuid
    type: uuid
    nullable: true
  - name: uuid
    type: uuid
    isPrimary: true
